In [75]:
from IPython.core.display import display, HTML
display(HTML("<style>.container { width:97.5% !important; }</style>"))

[autoreload of dops failed: Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/IPython/extensions/autoreload.py", line 244, in check
    superreload(m, reload, self.old_objects)
  File "/anaconda3/lib/python3.6/site-packages/IPython/extensions/autoreload.py", line 376, in superreload
    module = reload(module)
  File "/anaconda3/lib/python3.6/imp.py", line 315, in reload
    return importlib.reload(module)
  File "/anaconda3/lib/python3.6/importlib/__init__.py", line 166, in reload
    _bootstrap._exec(spec, module)
  File "<frozen importlib._bootstrap>", line 618, in _exec
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 781, in get_code
  File "<frozen importlib._bootstrap_external>", line 741, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/yuanhengwang/Desktop/Classes/Spring 2019/AM221 - advanced optimization/

In [76]:
%reload_ext autoreload
%autoreload 2
import numpy as np
from dops import *

In [77]:
def generate_data(u, theta, C, n, k):
    S = np.zeros((n, len(u)))
    z = np.zeros(n)
    for i in range(n):
        features = np.random.choice(u, size=k, replace=False)
        S[i] = np.array([1 if j in features else 0 for j in range(len(u))])
        cs = []
        for f in features:
            for j in C[f]:
                if j not in cs:
                    cs.append(j)
        z[i] = np.sum(theta[cs])
    return S, z

k = 5
d = 20
u = np.arange(d)
theta = np.random.randint(100, size=d)
C = [np.random.choice(u, size=np.random.randint(1,8), replace=False) for _ in range(d)]
S, z = generate_data(u, theta, C, 90, k)
T, v = generate_data(u, theta, C, 10, k)

In [78]:
S[0]

array([0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 1., 0., 1., 0., 1., 0.,
       0., 0., 0.])

In [79]:
C

[array([17,  5, 10]),
 array([ 2, 16,  4, 11,  5, 10]),
 array([18]),
 array([ 1, 17,  8, 16,  0, 14]),
 array([ 1, 11]),
 array([11,  3]),
 array([ 4, 14, 13,  6, 12]),
 array([ 6,  4,  7, 13]),
 array([4]),
 array([9]),
 array([14,  7]),
 array([14,  8]),
 array([11]),
 array([10,  6,  1,  0]),
 array([6]),
 array([ 6,  4,  9, 15]),
 array([10,  1]),
 array([ 0, 13, 16,  6, 11]),
 array([19,  7,  9,  5]),
 array([15,  0, 11,  1,  2, 17,  8])]

In [82]:
indices_of_results = []
for i in range(1):
    k = 5
    d = 20
    u = np.arange(d)
    theta = np.random.randint(100, size=d)
    C = [np.random.choice(u, size=np.random.randint(1,8), replace=False) for _ in range(d)]
    S, z = generate_data(u, theta, C, 90, k)
    T, v = generate_data(u, theta, C, 10, k)
    res, pred_theta, max_item_index = dops(S, z, T, C, 6, 0.5, np.zeros(d), eta=0.02, iters=1500, verbose=True)
    max_item = v[max_item_index]
    v = sorted(v,reverse=True)
    indices_of_results.append(v.index(max_item))

[0. 0. 0. 0. 1. 0. 0. 1. 0. 1. 0. 0. 0. 0. 0. 1. 0. 1. 0. 0.]


IndexError: index 1 is out of bounds for axis 0 with size 1

In [63]:
##Expected the indices to be small 1 ~ 3 but instead the results are relatively high
##When we change the verbose to true, we find that our theta doesn't converge, which is unexpected.
indices_of_results 

[9, 1, 5, 8, 6, 8, 9, 5, 5, 4, 5, 6, 4, 0, 4, 1, 7, 9, 8, 1]

In [36]:
pred_theta, theta

(array([ 5.33333333e-02,  6.00000000e-02, -9.90527105e-15,  2.66666667e-02,
        -1.13333333e-01, -1.33333333e-02, -6.66666667e-03,  2.66666667e-02,
         3.33333333e-02, -3.33333333e-02, -8.19136425e-15,  6.66666667e-03,
        -2.66666667e-02,  6.66666667e-03,  4.66666667e-02, -2.00000000e-02,
         1.33333333e-02,  3.33333333e-02, -2.00000000e-02, -8.66666667e-02]),
 array([37, 10, 83, 13, 26, 82, 35, 47, 77, 93, 28, 64, 67, 44, 35, 61, 46,
         6, 51, 77]))

In [37]:
res

[0.16666666666659724,
 -0.1066666666667547,
 0.06666666666660068,
 0.14666666666659703,
 0.09999999999994141,
 0.09999999999991441,
 -0.10000000000008119,
 0.026666666666588665,
 0.11333333333325114,
 0.07999999999992463]